import ArmControl
import GazeAndPostureControl
import qi
import argparse
import sys
import time
import almath
from naoqi import ALProxy

pepper_ip = "128.237.247.249"

def main(session, speech):
    """
    This example uses the angleInterpolation method.
    """
    # Get the service ALMotion.
    arm = ArmControl.ArmControl(session)
    gp = GazeAndPostureControl.GazeAndPostureControl(session)
    speech.setParameter("speed", 100)
    condition = "cheat"
    cheatRounds = [1, 8, 15]  # cheat occurs on 4th, 8th, and 15th rounds

    #this is the random sequence generated by a python script
    sequence = [2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2]

    numRounds = 20
    #control
    try:
        for i in range(numRounds):
            speech.say("Even or odd?")
            user = raw_input("Wait for response (enter to continue, q exits)") #wait for human to respond
            if user == "q":
                raise StopException()
            speech.say("3 2 1")

            arm.makeChoice(sequence[i])

            if condition == "control" or i not in cheatRounds:
                # We are not cheating
                sayWinner(speech)
            else:
                option = raw_input("Press 1=robot can cheat, press 2=robot cannot cheat")
                if option == "1":
                    arm.changeChoice()
                else:
                    #increment rounds so that everything gets pushed back
                    numRounds = numRounds + 1
                    cheatRounds = [rnd+1 if rnd >= i else rnd for rnd in cheatRounds]
                    # for i in range(len(cheatRounds)):
                    #     if i <= cheatRounds[i]: #if the round has not passed
                    #         cheatRounds[i] = cheatRounds[i] + 1
                if condition == "cheat":
                    speech.say("I win")
                else:
                    speech.say("I lose")
            arm.rest()
    except StopException:
        print("Quitting")
    except KeyboardInterrupt:
        print("Caught keyboard interrupt, going to try to close everything normally")
        print("Interrupt again if this hangs")
    arm.close()
    gp.close()

def sayWinner(tts):
    option = raw_input("Press 1=win or 2=lose: ")
    if option == "1":
        tts.say("I win")
    elif option == "2":
        tts.say("I lose")
    elif option == "q":
        raise StopException()


class StopException(Exception):
    pass


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--ip", type=str, default=pepper_ip,
                        help="Robot IP address. On robot or Local Naoqi: use '127.0.0.1'.")
    parser.add_argument("--port", type=int, default=9559,
                        help="Naoqi port number")

    args = parser.parse_args()
    session = qi.Session()
    try:
        session.connect("tcp://" + args.ip + ":" + str(args.port))
    except RuntimeError:
        print("Can't connect to Naoqi at ip \"" + args.ip + "\" on port " + str(args.port) + ".\n"
              "Please check your script arguments. Run with -h option for help.")
        sys.exit(1)

    tts = ALProxy("ALTextToSpeech", pepper_ip, 9559)

    main(session, tts)
